# Generated by Django 3.2.5 on 2022-12-04 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebdevLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('webdev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.webdevpost')),
            ],
        ),
        migrations.CreateModel(
            name='WebdevComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('webpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.webdevpost')),
            ],
        ),
        migrations.AddField(
            model_name='webdevpost',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_by', through='core.WebdevLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
