# Generated by Django 3.2.16 on 2022-12-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221204_0851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webdevlike',
            unique_together={('user', 'webdev')},
        ),
    ]
